name: Deploy

on:
  push:
    branches:
      - master

jobs:

  build_and_deploy_dev_docs:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install ruby dependencies
        run: bundle install

      - name: Build static site
        run: bundle exec middleman build
